<<<<<<< HEAD
def get_example_patients():
    return [
        {
            "id": "P-001",
            "input": {
                "triage_level": 1,
                "age": 45,
                "needs_surgery": True,
                "needs_ventilator": False,
                "internal_bleeding": True,
                "available_doctors": 2,
                "available_or_rooms": 1,
                "available_icu_beds": 0,
                "available_ventilators": 0,
            },
            "expected": "IMMEDIATE_OR",
        },
        {
            "id": "P-002",
            "input": {
                "triage_level": 1,
                "age": 60,
                "needs_surgery": True,
                "needs_ventilator": False,
                "internal_bleeding": True,
                "available_doctors": 1,
                "available_or_rooms": 0,
                "available_icu_beds": 1,
                "available_ventilators": 1,
            },
            "expected": "WAITLIST",
        },
        {
            "id": "P-003",
            "input": {
                "triage_level": 2,
                "age": 70,
                "needs_surgery": False,
                "needs_ventilator": False,
                "internal_bleeding": False,
                "available_doctors": 3,
                "available_or_rooms": 2,
                "available_icu_beds": 2,
                "available_ventilators": 0,
            },
            "expected": "GENERAL_WARD",
        },
        {
            "id": "P-004",
            "input": {
                "triage_level": 2,
                "age": 55,
                "needs_surgery": False,
                "needs_ventilator": False,
                "internal_bleeding": False,
                "available_doctors": 2,
                "available_or_rooms": 1,
                "available_icu_beds": 0,
                "available_ventilators": 2,
            },
            "expected": "GENERAL_WARD",
        },
        {
            "id": "P-005",
            "input": {
                "triage_level": 2,
                "age": 68,
                "needs_surgery": False,
                "needs_ventilator": True,
                "internal_bleeding": False,
                "available_doctors": 2,
                "available_or_rooms": 1,
                "available_icu_beds": 1,
                "available_ventilators": 1,
            },
            "expected": "IMMEDIATE_ICU",
        },
         {
           "id": "P-006",
            "input": {
                "triage_level": 1,
                "age": 60,
                "needs_surgery": True,
                "needs_ventilator": True,
                "internal_bleeding": False,
                "available_doctors": 1,
                "available_or_rooms": 1,
                "available_icu_beds": 1,
                "available_ventilators": 1,
            },
            "expected": "IMMEDIATE_OR"
        },
        {
            "id": "P-007",
            "input": {
                "triage_level": 4,
                "age": 30,
                "needs_surgery": False,
                "needs_ventilator": False,
                "internal_bleeding": False,
                "available_doctors": 0,
                "available_or_rooms": 0,
                "available_icu_beds": 0,
                "available_ventilators": 0,
            },
            "expected": "GENERAL_WARD",
        },
        {
            "id": "P-008",
            "input": {
                "triage_level": 1,
                "age": 3,
                "needs_surgery": True,
                "needs_ventilator": False,
                "internal_bleeding": False,
                "available_doctors": 1,
                "available_or_rooms": 0,
                "available_icu_beds": 1,
                "available_ventilators": 1,
            },
            "expected": "ESCALATE_TRANSFER"
            },
    ]
=======
def get_example_patients():
    return [
        {
            "id": "P-001",
            "input": {
                "triage_level": 1,
                "age": 45,
                "needs_surgery": True,
                "needs_ventilator": False,
                "internal_bleeding": True,
                "available_doctors": 2,
                "available_or_rooms": 1,
                "available_icu_beds": 0,
                "available_ventilators": 0,
            },
        },
        {
            "id": "P-002",
            "input": {
                "triage_level": 1,
                "age": 60,
                "needs_surgery": True,
                "needs_ventilator": False,
                "internal_bleeding": True,
                "available_doctors": 1,
                "available_or_rooms": 0,
                "available_icu_beds": 1,
                "available_ventilators": 1,
            },
        },
        {
            "id": "P-003",
            "input": {
                "triage_level": 2,
                "age": 70,
                "needs_surgery": False,
                "needs_ventilator": False,
                "internal_bleeding": False,
                "available_doctors": 3,
                "available_or_rooms": 2,
                "available_icu_beds": 2,
                "available_ventilators": 0,
            },
        },
        {
            "id": "P-004",
            "input": {
                "triage_level": 2,
                "age": 55,
                "needs_surgery": False,
                "needs_ventilator": False,
                "internal_bleeding": False,
                "available_doctors": 2,
                "available_or_rooms": 1,
                "available_icu_beds": 0,
                "available_ventilators": 2,
            },
        },
        {
            "id": "P-005",
            "input": {
                "triage_level": 2,
                "age": 68,
                "needs_surgery": False,
                "needs_ventilator": True,
                "internal_bleeding": False,
                "available_doctors": 2,
                "available_or_rooms": 1,
                "available_icu_beds": 1,
                "available_ventilators": 1,
            },
        },
        {
            "id": "P-006",
            "input": {
                "triage_level": 1,
                "age": 60,
                "needs_surgery": True,
                "needs_ventilator": True,
                "internal_bleeding": False,
                "available_doctors": 1,
                "available_or_rooms": 1,
                "available_icu_beds": 1,
                "available_ventilators": 1,
            },
        },
        {
            "id": "P-007",
            "input": {
                "triage_level": 4,
                "age": 30,
                "needs_surgery": False,
                "needs_ventilator": False,
                "internal_bleeding": False,
                "available_doctors": 0,
                "available_or_rooms": 0,
                "available_icu_beds": 0,
                "available_ventilators": 0,
            },
        },
        {
            "id": "P-008",
            "input": {
                "triage_level": 1,
                "age": 3,
                "needs_surgery": True,
                "needs_ventilator": False,
                "internal_bleeding": False,
                "available_doctors": 1,
                "available_or_rooms": 0,
                "available_icu_beds": 1,
                "available_ventilators": 1,
            },
        },
>>>>>>> 68bb209bb74680a3757ce1748e0253e924ff7993
